server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${INVENTORY_POSTGRES_HOST:localhost}:${INVENTORY_POSTGRES_PORT:5434}/${INVENTORY_POSTGRES_DB:inventory_database}?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: ${INVENTORY_POSTGRES_USER:root}
    password: ${INVENTORY_POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8082}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8082/api/v1/auth/jwks}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  outbox:
    relay-delay-ms: ${OUTBOX_RELAY_DELAY_MS:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"
