ALTER TABLE product_variant ADD COLUMN IF NOT EXISTS color VARCHAR(100);
ALTER TABLE product_variant ADD COLUMN IF NOT EXISTS color_hex VARCHAR(20);
ALTER TABLE product_variant ADD COLUMN IF NOT EXISTS size VARCHAR(100);

ALTER TABLE product_variant ALTER COLUMN sku DROP NOT NULL;

