server:
  port: 8081
  servlet:
    context-path: /vinh


spring:
  application:
    name: clothes-retail-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/fashion_database?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

openapi:
  service:
    api-docs: fashion-api-service
    server: http://localhost:8081/vinh
    title: API Service
    version: v1.0.0

